
INSERT INTO pronolegaforum.valori_pronostici(stagione, id_competizione, valori_pronostici)
VALUES (2018, 
        1, 
        '{"Atalanta",
"Bologna",
"Cagliari",
"Chievo",
"Empoli",
"Fiorentina",
"Frosinone",
"Genoa",
"Inter",
"Juventus",
"Lazio",
"Milan",
"Napoli",
"Parma",
"Roma",
"Sampdoria",
"Sassuolo",
"Spal",
"Torino",
"Udinese"}'
        );

INSERT INTO pronolegaforum.valori_pronostici(stagione, id_competizione, valori_pronostici)
VALUES (2018, 
        3,
'{"Arsenal",
"Bournemouth",
"Brighton",
"Burnley",
"Cardiff",
"Chelsea",
"Crystal Palace",
"Everton",
"Fulham",
"Huddersfield",
"Leicester",
"Liverpool",
"Manchester City",
"Manchester Utd",
"Newcastle",
"Southampton",
"Tottenham",
"Watford",
"West Ham",
"Wolves"}'
);

INSERT INTO pronolegaforum.valori_pronostici(stagione, id_competizione, valori_pronostici)
VALUES (2018, 
        5,
'{"Ascoli",
"Benevento",
"Brescia",
"Carpi",
"Cittadella",
"Cosenza",
"Cremonese",
"Crotone",
"Foggia",
"Lecce",
"Livorno",
"Padova",
"Palermo",
"Perugia",
"Pescara",
"Salernitana",
"Spezia",
"Venezia",
"Verona"}'
);

INSERT INTO pronolegaforum.valori_pronostici(stagione, id_competizione, valori_pronostici)
VALUES (2018, 
        4,
'{"AEK Athens (GRE)",
"Ajax (NED)",
"Atlético Madrid (ESP)",
"Barcellona (ESP)",
"BATE Borisov (BLR)",
"Bayern München (GER)",
"Benfica (POR)",
"Borussia Dortmund (GER)",
"Club Brugge (BEL)",
"Crvena zvezda (SRB)",
"CSKA Moskva (RUS)",
"Dinamo Zagreb (CRO)",
"Dynamo Kyiv (UKR)",
"Galatasaray (TUR)",
"Hoffenheim (GER)",
"Inter (ITA)",
"Juventus (ITA)",
"Liverpool (ENG)",
"Lokomotiv Moskva (RUS)",
"Lyon (FRA)",
"Manchester City (ENG)",
"Manchester United (ENG)",
"Monaco (FRA)",
"Napoli (ITA)",
"PAOK (GRE)",
"Porto (POR)",
"PSG (FRA)",
"Real Madrid (ESP)",
"Roma (ITA)",
"Salzburg (AUT)",
"Schalke (GER)",
"Shakhtar Donetsk (UKR)",
"Tottenham Hotspur (ENG) ",
"Valencia (ESP)",
"Vidi (HUN)",
"Viktoria Plzeň (CZE)"}'
);

INSERT INTO pronolegaforum.valori_pronostici(stagione, id_competizione, valori_pronostici)
VALUES (2018, 
        2,
'{"ACQUAH Afriyie",
"ADJAPONG Claud",
"ALLAN Marques Loureiro",
"ANDERSON Djavan",
"ANTENUCCI Mirco",
"ARAMU Mattia",
"AVENATTI Felipe Nicolas",
"BABACAR Khouma El Hadji",
"BACCA Carlos Arturo",
"BADELJ Milan",
"BADU Emmanuel Agyemang",
"BALDASSIN Luca",
"BALIC Andrija",
"BARAK Antonin",
"BARAYE Bertrand Yves",
"BARELLA Nicolo''",
"BARILLA'' Antonino",
"BARRETO Edgar Osvaldo",
"BARROW Musa",
"BASELLI Daniele",
"BEGHETTO Andrea",
"BEHRAMI Valon",
"BELOTTI Andrea",
"BENASSI Marco",
"BENNACER Ismael",
"BENTANCUR Rodrigo",
"BERARDI Domenico",
"BERENGUER Alejandro",
"BERISHA Valon",
"BERNARDESCHI Federico",
"BERTOLACCI Andrea",
"BESEA Prince Emmanuel",
"BESSA Daniel",
"BIABIANY Jonathan Ludovic",
"BIFULCO Alfredo",
"BIGLIA Lucas Rodrigo",
"BIRSA Valter",
"BOATENG Kevin-Prince",
"BOGA Jeremie",
"BONAVENTURA Giacomo",
"BORINI Fabio",
"BORJA VALERO Iglesias",
"BOURABIA Mehdi",
"BRADARIC Filip",
"BRIGHI Matteo",
"BRIGNOLA Enrico",
"BROZOVIC Marcelo",
"BUCHEL Marcel",
"BUTIC Karlo",
"CAICEDO Felipe Salvador",
"CALAIO'' Emanuele",
"CALHANOGLU Hakan",
"CALIGARA Fabrizio",
"CALLEGARI Lorenzo",
"CALLEJON Jose'' Maria",
"CAN Emre",
"CANDELA Antonio",
"CANDREVA Antonio",
"CAPEZZI Leonardo",
"CAPONE Christian",
"CAPRARI Gianluca",
"CAPUTO Francesco",
"CARRIERO Giuseppe",
"CASSATA Francesco",
"CASTRO Lucas Nahuel",
"CATALDI Danilo",
"CERAVOLO Giovanni Fabio",
"CERRI Alberto",
"CHIBSAH Yussif Raman",
"CHIESA Federico",
"CIANO Camillo",
"CICIRETTI Amato",
"CIGARINI Luca",
"CINELLI Antonio",
"CIOFANI Daniel",
"CITRO Nicola",
"CLEMENZA Luca",
"COLOMBATTO Santiago",
"CONTI Andrea",
"CORIC Ante",
"CORNELIUS Andreas",
"CORREA Carlos Joaquin",
"COSTA Filippo",
"COULIBALY Mamadou",
"CRISETIG Lorenzo",
"CRISTANTE Bryan",
"CRISTOFORO Sebastian Carlos",
"CUADRADO Juan Guillermo",
"CUTRONE Patrick",
"D''ALESSANDRO Marco",
"DA CRUZ Alessio",
"DABO Bryan",
"DALMONTE Nicola",
"DAMASCAN Vitalie",
"DE PAUL Rodrigo Javier",
"DE ROON Marten",
"DE ROSSI Daniele",
"DEFREL Gregoire",
"DEIOLA Alessandro",
"DEPAOLI Fabio",
"DESSENA Daniele",
"DESTRO Mattia",
"DEZI Jacopo",
"DI FRANCESCO Federico",
"DI GAUDIO Antonio",
"DI GENNARO Davide",
"DIAWARA Amadou",
"DIONISI Federico",
"DJORDJEVIC Filip",
"DJURICIC Filip",
"DONSAH Godfred",
"DOUGLAS COSTA de Souza",
"DUNCAN Joseph Alfred",
"DYBALA Paulo Bruno",
"DZEKO Edin",
"DZEMAILI Blerim",
"EDERA Simone",
"EL SHAARAWY Stephan",
"EMMERS Xian",
"ESPOSITO Salvatore",
"EVERTON LUIZ Guimaraes Bilher",
"EYSSERIC Valentin",
"FALCINELLI Diego",
"FANTACCI Tommaso",
"FARAGO'' Paolo Pancrazio",
"FARES Mohamed Salim",
"FARIAS Diego da Silva",
"FAVILLI Andrea",
"FERNANDES Edmilson",
"FLOCCARI Sergio",
"FLORO FLORES Antonio",
"FOFANA Seko Mohamed",
"FRATTESI Davide",
"FREULER Remo",
"GABBIA Matteo",
"GAGLIARDINI Roberto",
"GALABINOV Andrey Asenov",
"GALANO Cristian",
"GARRITANO Luca",
"GAUDINO Gianluca",
"GERSON Santos da Silva",
"GIACCHERINI Emanuele",
"GNOUKOURI Assane Demoya",
"GOMEZ Alejandro Dario",
"GONALONS Maxime",
"GORI Mirko",
"GOSENS Robin",
"GRAICIAR Martin",
"GRASSI Alberto",
"HALILOVIC Alen",
"HALLFREDSSON Emil",
"HAMSIK Marek",
"HAN Kwang-Song",
"HETEMAJ Perparim",
"HIGUAIN Gonzalo Gerardo",
"HILJEMARK Oscar Karl",
"IAGO FALQUE Silva",
"ICARDI Mauro Emanuel",
"ILICIC Josip",
"IMMOBILE Ciro",
"INGELSSON Svante Ulf",
"INGLESE Roberto",
"INIGUEZ Gaspar Emanuel",
"INSIGNE Lorenzo",
"IONITA Artur",
"IVAN David",
"JAKUPOVIC Arnel",
"JALLOW Lamin",
"JANKTO Jakub",
"JOAO MARIO Naval da Costa",
"JOAO PEDRO Geraldino",
"JORDAO Bruno Andre'' Cavaco",
"KARAMOH Yann",
"KATUMA Aron",
"KEAN Moise Bioty",
"KEITA Balde Diao",
"KESSIE'' Franck Yannick",
"KHEDIRA Sami",
"KISHNA Ricardo",
"KIYINE Sofian",
"KLUIVERT Justin",
"KONE Panagiotis Georgios",
"KOUAME'' Christian Michael",
"KOWNACKI Dawid",
"KREJCI Ladislav",
"KRUNIC Rade",
"KURTIC Jasmin",
"LA GUMINA Antonino",
"LAPADULA Gianluca",
"LASAGNA Kevin",
"LAXALT Diego Sebastian",
"LAZOVIC Darko",
"LAZZARI Manuel",
"LEIVA Lucas Pezzini",
"LERIS Mehdi",
"LINETTY Karol",
"LJAJIC Adem",
"LOCATELLI Manuel",
"LOLLO Lorenzo",
"LOMBARDI Cristiano",
"LUIS ALBERTO Romero Alconchel",
"LUKIC Sasa",
"LULIC Senad",
"MACHIS Darwin Daniel",
"MAGNANELLI Francesco",
"MAIELLO Raffaele",
"MALLE'' Aly",
"MANDRAGORA Rolando",
"MANDZUKIC Mario",
"MARCHISIO Claudio",
"MARILUNGO Guido",
"MARTINEZ Lautaro Javier",
"MARUSIC Adam",
"MATARESE Luca",
"MATRI Alessandro",
"MATUIDI Blaise",
"MAURI Jose'' Agustin",
"MAZZITELLI Luca",
"MCHEDLIDZE Levan",
"MEDEIROS Iuri Jose'' Picanco",
"MEGGIORINI Riccardo",
"MEITE'' Soualiho",
"MERTENS Dries",
"MICHAEL Kingsley Dogo",
"MICIN Petar",
"MILIK Arkadiusz",
"MILINKOVIC-SAVIC Sergej",
"MINALA Joseph Marie",
"MIRALLAS Kevin Antonio",
"MISSIROLI Simone",
"MONCINI Gabriele",
"MONTOLIVO Riccardo",
"MORRISON Ravel Ryan",
"MRAZ Samuel",
"MUNARI Gianni",
"MURANO Jacopo",
"MURGIA Alessandro",
"NAGY Adam",
"NAINGGOLAN Radja",
"NETO Pedro Lomba",
"NIANG M''baye",
"NIKOLIC Lazar",
"NINKOVIC Nikola",
"NORGAARD Christian Thers",
"OBI Joel Chukwuma",
"ODGAARD Jens",
"OIKONOMIDIS Christopher James",
"OKWONKWO Orji",
"OMEONGA Stephane",
"ORSOLINI Riccardo",
"OUNAS Adam",
"PADOIN Simone",
"PAGANINI Luca",
"PAJAC Marko",
"PALACIO Rodrigo Sebastian",
"PALOSCHI Alberto",
"PANDEV Goran",
"PARIGINI Vittorio",
"PAROLO Marco",
"PASALIC Mario",
"PASTORE Javier Matias",
"PAVOLETTI Leonardo",
"PEETERS Daouda",
"PELLEGRINI Lorenzo",
"PELLISSIER Sergio",
"PEREA Brayan Andres",
"PERICA Stipe",
"PERISIC Ivan",
"PEROTTI Diego",
"PESSINA Matteo",
"PETAGNA Andrea",
"PIATEK Krzysztof",
"PINAMONTI Andrea",
"PJACA Marko",
"PJANIC Miralem",
"POLI Andrea",
"POLITANO Matteo",
"PONTISSO Simone",
"PRAET Dennis",
"PUCCIARELLI Manuel",
"PULGAR Erick Antonio",
"PUSSETTO Ignacio",
"QUAGLIARELLA Fabio",
"RADOVANOVIC Ivan",
"RAMIREZ Gaston Exequiel",
"RASPADORI Giacomo",
"RECA Arkadiusz",
"RIGONI Luca",
"RIGONI Nicola",
"RINCON Tomas Eduardo",
"RIZZO Luca",
"RODRIGUEZ Alejandro",
"ROG Marko",
"ROLANDO Gabriele",
"ROLON Esteban Leonardo",
"ROMULO Souza Orestes",
"RONALDO Cristiano",
"ROSSI Alessandro",
"RUIZ Fabian",
"SAMMARCO Paolo",
"SANDRO Raniere Guimaraes Cordeiro",
"SANTANDER Federico Javier",
"SAPONARA Riccardo",
"SAU Marco",
"SCAGLIA Luigi",
"SCAMACCA Gianluca",
"SCAVONE Manuel",
"SCHIATTARELLA Pasquale",
"SCHICK Patrik",
"SCOZZARELLA Matteo",
"SENSI Stefano",
"SILIGARDI Luca",
"SIMEONE Giovanni Pablo",
"SODDIMO Danilo",
"SOTTIL Riccardo",
"SOWE Ali",
"SPINAZZOLA Leonardo",
"SPROCATI Mattia",
"STEPINSKI Mariusz",
"STIJEPOVIC Ognjen",
"STROOTMAN Kevin Johannes",
"STULAC Leo",
"SUSO Jesus Fernandez",
"SVANBERG Mattias",
"THEREAU Cyril",
"TRAORE'' Hamed Junior",
"TROTTA Marcello",
"TUMMINELLO Marco",
"UNDER Cengiz",
"VACCA Antonio Junior",
"VALDIFIORI Mirko",
"VALENCIA Juan Manuel",
"VALOTI Mattia",
"VALZANIA Luca",
"VECINO Matias",
"VERDI Simone",
"VERETOUT Jordan Marcel",
"VERRE Valerio",
"VIEIRA Ronaldo",
"VIGNATO Emanuel",
"VINICIUS Carlos Alves",
"VITALE Mattia",
"VIVIANI Federico",
"VIZEU Felipe dos Reis",
"VLAHOVIC Dusan",
"VUTOV Antonio",
"YOUNES Amin",
"ZAJC Miha",
"ZANIMACCHIA Luca",
"ZANIOLO Nicolo''",
"ZAPATA Duvan Esteban",
"ZEKHNINI Rafik",
"ZIELINSKI Piotr Sebastian"}'
);